# Generated by Django 6.0.2 on 2026-02-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        db_index=True, unique=True, verbose_name="Номер столика"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(verbose_name="Вместимость"),
                ),
                (
                    "type_table",
                    models.CharField(
                        choices=[("Обычный", "Common"), ("VIP", "Vip")],
                        verbose_name="Тип столика",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество гостей"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time_from", models.TimeField(verbose_name="Время начала")),
                ("time_to", models.TimeField(verbose_name="Время окончания")),
                ("customer", models.CharField(max_length=50, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("comment", models.CharField(max_length=255, verbose_name="Пожелания")),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="Стоимость"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Открыта", "Open"),
                            ("Закрыта", "Closed"),
                            ("Отменена", "Cancelled"),
                        ],
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["-created_at"],
            },
        ),
    ]
